table Customer_Key
	lineageTag: 37b422f1-4cc5-4298-b402-817130fc2a3e

	column Customer_Key
		dataType: int64
		formatString: 0
		lineageTag: 0e9d18a1-a5c8-4673-a667-40d3920f004f
		summarizeBy: count
		sourceColumn: Customer_Key

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: string
		lineageTag: 2f7d3c41-0007-4e60-8c13-b4b04365ce96
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	partition Customer_Key = m
		mode: import
		queryGroup: Surrogate_Keys
		source =
				let
				    Source = stg_Customer,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"CustomerKey"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CustomerKey"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Customer_Key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

