table Customer
	lineageTag: cba8a3f8-91f6-4a41-a05e-75027e92e066

	column Customer_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bea002c3-71f7-461d-9967-9f0b004aa326
		summarizeBy: none
		sourceColumn: Customer_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: string
		lineageTag: 932f7ff2-7a05-4995-a305-1484e48e5ec1
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 5078323c-4561-4e41-b94b-10dd0e8b1624
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 255ea007-9db5-45aa-bd2c-b8332268fda2
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Customer Company'
		dataType: string
		lineageTag: f1407a77-4d61-4aef-92b1-c2e72425524b
		summarizeBy: none
		sourceColumn: Customer Company

		annotation SummarizationSetBy = Automatic

	column 'Contact Name'
		dataType: string
		lineageTag: eb4de332-07a4-45e4-aa40-10a6a7458753
		summarizeBy: none
		sourceColumn: Contact Name

		annotation SummarizationSetBy = Automatic

	column 'Contact Title'
		dataType: string
		lineageTag: 2f6ff1e6-77c1-48ad-918c-5aaf55c4d897
		summarizeBy: none
		sourceColumn: Contact Title

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: f0ecf228-89b6-4c22-9814-3c0bbedff5ed
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: ad416ff4-aa0d-4c21-a459-1c7c2ac76f15
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 01b2e74e-5de9-417d-90e6-febf76597b85
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 802ff651-6443-4bd0-9b38-14d1e7044b05
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: cb7e1104-ac30-495f-88c0-8bfceff437eb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Customer,
				    #"Merged Queries" = Table.NestedJoin(Source, {"CustomerKey"}, lkp_Customer_Key, {"CustomerKey"}, "sil_Customer (2)", JoinKind.LeftOuter),
				    #"Expanded sil_Customer (2)" = Table.ExpandTableColumn(#"Merged Queries", "sil_Customer (2)", {"Customer_Key"}, {"Customer_Key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded sil_Customer (2)",{"Customer_Key", "CustomerKey", "Address", "City", "CompanyName", "ContactName", "ContactTitle", "Country", "Fax", "Phone", "PostalCode", "Region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"CompanyName", "Customer Company"}, {"ContactName", "Contact Name"}, {"ContactTitle", "Contact Title"}, {"PostalCode", "Postal Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

