table Filters
	lineageTag: dcdd9820-6a27-48f6-a4fe-74dc0be41933

	column StatusID
		dataType: string
		isHidden
		lineageTag: 67bd2ec5-fc56-401f-b623-c0bcc82a8b04
		summarizeBy: none
		sourceColumn: StatusID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		lineageTag: e610ec12-28fa-49d4-aa7c-dc950c8cc681
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	partition Filters = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_OrderStatus,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Description", "Order Status"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"StatusID", "Order Status"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

