table Invoice
	lineageTag: 743ca6a0-54d6-4b7a-a1f3-63b60537f89c

	column CustomerID
		dataType: string
		lineageTag: ffcb56a2-e73f-486d-a88b-caf07acf478b
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Freight
		dataType: decimal
		lineageTag: 474365da-87ed-494e-aff6-8a7349923262
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: bcd12dd4-f904-45bc-b075-a0f62ae7a0d6
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: f1d55fb2-9465-44bd-ae25-9b30a90d1881
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3ce298aa-9f96-40c0-97da-e5cee93f1bc6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b5db21bd-c7a8-42f6-a8b4-1529a69f86bb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column RequiredDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9dcdaa8-5d4e-4785-b2f6-c67791ded8ff
		summarizeBy: none
		sourceColumn: RequiredDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipName
		dataType: string
		lineageTag: 6a318c2f-8a62-471b-8324-7c442804d4b4
		summarizeBy: none
		sourceColumn: ShipName

		annotation SummarizationSetBy = Automatic

	column ShipperName
		dataType: string
		lineageTag: eeef93de-2958-41b7-b61b-c2c029890be9
		summarizeBy: none
		sourceColumn: ShipperName

		annotation SummarizationSetBy = Automatic

	column ShipPostalCode
		dataType: string
		lineageTag: 04d06b04-8639-4d38-83d8-f6e003b3ab3b
		summarizeBy: none
		sourceColumn: ShipPostalCode

		annotation SummarizationSetBy = Automatic

	column ShipRegion
		dataType: string
		lineageTag: 0022b461-180a-4ccb-9a4f-4f95a7640b9d
		summarizeBy: none
		sourceColumn: ShipRegion

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		lineageTag: 6b9d2a69-c945-4b9a-aa66-e999d9546146
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShipCountry
		dataType: string
		lineageTag: a2e2c965-e2d1-4b17-931a-4b36b07ebf59
		summarizeBy: none
		sourceColumn: ShipCountry

		annotation SummarizationSetBy = Automatic

	column ShipCity
		dataType: string
		lineageTag: 8963a3e4-6939-4ef1-95fc-9586acaba151
		summarizeBy: none
		sourceColumn: ShipCity

		annotation SummarizationSetBy = Automatic

	column ShipAddress
		dataType: string
		lineageTag: cf428a27-b97e-4d4e-9524-f6e94b579e46
		summarizeBy: none
		sourceColumn: ShipAddress

		annotation SummarizationSetBy = Automatic

	column ShippedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9f7a2f0-17ec-4b73-8263-0b1be005b009
		summarizeBy: none
		sourceColumn: ShippedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Invoice = m
		mode: import
		queryGroup: Silver
		source =
				let
				    Source = CSVs,
				    Data = Source{[#"Folder Path"=DataFolder,Name="Invoices.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Data,[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", type text}, {"Freight", Currency.Type}, {"OrderID", Int64.Type}, {"ProductName", type text}, {"Quantity", Int64.Type}, {"Region", type text}, {"RequiredDate", type text}, {"ShipName", type text}, {"ShippedDate", type text}, {"ShipperName", type text}, {"ShipPostalCode", type text}, {"ShipRegion", type text}, {"UnitPrice", Currency.Type}, {"ShipCountry", type text}, {"ShipCity", type text}, {"ShipAddress", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "ShippedDateClean", each if not Text.Contains([ShippedDate], "/") then null else [ShippedDate]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Added Conditional Column", {{"RequiredDate", type datetime}, {"ShippedDateClean", type datetime}}, "en-US"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"ShippedDateClean", type date}, {"RequiredDate", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"ShippedDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ShippedDateClean", "ShippedDate"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

