table OrderDetail
	lineageTag: a4d16831-b4f0-4b32-8d29-ae8b425ec7c5

	column OrderID_FK
		dataType: int64
		formatString: 0
		lineageTag: 05d0b437-9a18-4a7c-8bc8-9cc2f2e47864
		summarizeBy: sum
		sourceColumn: OrderID_FK

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 1f87f5d5-1cc2-4bcc-a7bf-cd54d8889116
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 687f8a97-aaca-427a-bee7-383b0e2c70f5
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3bf35802-cb2b-43ff-a814-ecc746a2cc9a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 92e80198-e788-4354-bc16-e3c0afaa6674
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ShipVia
		dataType: string
		lineageTag: 602d2760-1145-4d8b-9cdf-886d6b9d8315
		summarizeBy: none
		sourceColumn: ShipVia

		annotation SummarizationSetBy = Automatic

	column OrderStatus
		dataType: string
		lineageTag: af5f15bb-f3b8-47a6-b01a-d7082619a042
		summarizeBy: none
		sourceColumn: OrderStatus

		annotation SummarizationSetBy = Automatic

	partition OrderDetail = m
		mode: import
		queryGroup: Silver
		source =
				let
				    Source = CSVs,
				    Data = Source{[#"Folder Path"=DataFolder,Name="OrdersDetails.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Data,[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID_FK", Int64.Type}, {"Discount", type number}, {"ProductID", Int64.Type}, {"Quantity", Int64.Type}, {"UnitPrice", Currency.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"OrderID_FK", "Discount", "ProductID", "Quantity", "UnitPrice", "ShipVia", "Status"}),
				    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns", {"Status"}, OrderStatus, {"StatusCode"}, "OrderStatus", JoinKind.LeftOuter),
				    #"Expanded OrderStatus" = Table.ExpandTableColumn(#"Merged Queries", "OrderStatus", {"Description"}, {"OrderStatus.Description"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded OrderStatus", "OrderStatus", each if [OrderStatus.Description] = null then "Unknown" else [OrderStatus.Description]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Status", "OrderStatus.Description"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"OrderID_FK", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

