table Order
	lineageTag: a83682d0-d880-420b-9f64-53e7173217af

	column OrderID
		dataType: string
		lineageTag: 23b59395-819f-4a86-bf0d-9e23d0dba01a
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9418ab6f-7d25-415d-adcc-a39663d06ee1
		summarizeBy: count
		sourceColumn: OrderDate_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Customer_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 646389e4-0e65-401b-95af-03c375ed9fae
		summarizeBy: none
		sourceColumn: Customer_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Employee_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3fbadc2d-361f-4ec0-82ad-9336e3173c94
		summarizeBy: none
		sourceColumn: Employee_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0441ddfc-71de-44bc-b85c-480606c53688
		summarizeBy: average
		sourceColumn: Discount

		annotation SummarizationSetBy = User

	column Product_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d3a76390-3543-45d8-acdf-d304435f8158
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: 3f43f193-6bdb-4de7-917b-8da9739be1cc
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 776cb950-2827-43db-bff5-aa5a6854112a
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Order_Shipper_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0c2939f6-1ba4-4b46-abc5-bf577c84826a
		summarizeBy: count
		sourceColumn: Order_Shipper_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderStatus_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 60dcbefe-2050-4877-a21d-491dea1b519d
		summarizeBy: none
		sourceColumn: OrderStatus_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Supplier_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 85fad3e9-d5ac-4ee3-af2e-b495e7e78b69
		summarizeBy: none
		sourceColumn: Supplier_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Invoice.Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 325fad6b-4904-4144-9cda-1a58e21d5a98
		summarizeBy: sum
		sourceColumn: Invoice.Quantity

		annotation SummarizationSetBy = Automatic

	column 'Invoice.Freight'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f91ef161-117b-48aa-9227-b08a1e2d74f0
		summarizeBy: none
		sourceColumn: Invoice.Freight

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Invoice.Invoice Region'
		dataType: string
		lineageTag: a620ab3e-5429-431f-a79e-7fb2082cddcd
		summarizeBy: none
		sourceColumn: Invoice.Invoice Region

		annotation SummarizationSetBy = Automatic

	column 'Invoice.UnitPrice'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6cb6eb6f-2382-472b-b12e-1e00845352c9
		summarizeBy: average
		sourceColumn: Invoice.UnitPrice

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Invoice.Shipment_Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 16acab83-1b68-40d6-96bb-7c434c03ec7d
		summarizeBy: none
		sourceColumn: Invoice.Shipment_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Invoice.Shipper_Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9fe20197-1889-4198-a40a-150948951e3d
		summarizeBy: none
		sourceColumn: Invoice.Shipper_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Invoice.RequiredDate_Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bcde8db6-fd0b-477e-b2da-04f60c50220b
		summarizeBy: none
		sourceColumn: Invoice.RequiredDate_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Invoice.ShippedDate_Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2feb98bb-0ec3-4a8b-9c5c-67b7b2f1c056
		summarizeBy: none
		sourceColumn: Invoice.ShippedDate_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Order = m
		mode: import
		queryGroup: Facts
		source =
				let
				    fnToDateKey = (inputDate) =>
				    let
				        // Ensure we are working with a proper Date type first
				        d = if inputDate is date then inputDate else Date.From(inputDate),
				        // Simple math: (Year * 10000) + (Month * 100) + Day
				        // Example: (1971 * 10000) + (4 * 100) + 6 = 19710406
				        Key = (Date.Year(d) * 10000) + (Date.Month(d) * 100) + Date.Day(d)
				    in
				        Key,
				    Source = stg_Order,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"PK_OrderID", "OrderID"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"CustomerID"}, lkp_Customer_Key, {"CustomerKey"}, "lkp_Customer_Key", JoinKind.LeftOuter),
				    #"Expanded lkp_Customer_Key" = Table.ExpandTableColumn(#"Merged Queries", "lkp_Customer_Key", {"Customer_Key"}, {"Customer_Key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded lkp_Customer_Key",{"OrderID", "Customer_Key", "CustomerID", "EmployeeID", "OrderDate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"EmployeeID", "Employee_Key"}}),
				    #"DateToKey" = Table.AddColumn(#"Renamed Columns1","OrderDate_Key", each fnToDateKey([OrderDate]), Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(DateToKey,{{"OrderDate_Key", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"OrderDate_Key", "Employee_Key", "Customer_Key", "OrderID"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Other Columns",{"OrderID", "OrderDate_Key", "Customer_Key", "Employee_Key"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Reordered Columns1", {"OrderID"}, stg_OrderDetail, {"OrderID_FK"}, "stg_OrderDetail", JoinKind.LeftOuter),
				    #"Expanded stg_OrderDetail" = Table.ExpandTableColumn(#"Merged Queries1", "stg_OrderDetail", {"OrderID_FK", "Discount", "ProductID", "Quantity", "UnitPrice", "ShipVia", "Status"}, {"OrderID_FK", "Discount", "ProductID", "Quantity", "UnitPrice", "ShipVia", "Status"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded stg_OrderDetail", {"Status"}, lkp_OrderStatus_Key, {"OrderStatus"}, "lkp_OrderStatus_Key", JoinKind.LeftOuter),
				    #"Expanded lkp_OrderStatus_Key" = Table.ExpandTableColumn(#"Merged Queries3", "lkp_OrderStatus_Key", {"OrderStatus_Key"}, {"OrderStatus_Key"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded lkp_OrderStatus_Key",{{"Discount", Percentage.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type1",{{"ShipVia", "Order_Shipper_Key"}, {"UnitPrice", "Unit Price"}, {"ProductID", "Product_Key"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns4",{"OrderID_FK"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Columns", {"Product_Key"}, lkp_Product_Key, {"Product_Key"}, "lkp_Product_Key", JoinKind.LeftOuter),
				    #"Expanded lkp_Product_Key" = Table.ExpandTableColumn(#"Merged Queries2", "lkp_Product_Key", {"Supplier_Key"}, {"Supplier_Key"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded lkp_Product_Key",{"Status"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Removed Columns1", {"OrderID", "Product_Key"}, Invoice, {"OrderID", "Product_Key"}, "Invoice", JoinKind.LeftOuter),
				    #"Expanded Invoice" = Table.ExpandTableColumn(#"Merged Queries4", "Invoice", {"Quantity", "Freight", "Invoice Region", "RequiredDate", "UnitPrice", "ShippedDate", "Shipment_Key", "Shipper_Key"}, {"Invoice.Quantity", "Invoice.Freight", "Invoice.Invoice Region", "Invoice.RequiredDate", "Invoice.UnitPrice", "Invoice.ShippedDate", "Invoice.Shipment_Key", "Invoice.Shipper_Key"}),
				    #"DateToKey2" = Table.AddColumn(#"Expanded Invoice","Invoice.RequiredDate_Key", each fnToDateKey([Invoice.RequiredDate]), Int64.Type),
				    #"DateToKey3" = Table.AddColumn(#"DateToKey2","Invoice.ShippedDate_Key", each fnToDateKey([Invoice.ShippedDate]), Int64.Type),
				    #"Removed Columns2" = Table.RemoveColumns(DateToKey3,{"Invoice.RequiredDate", "Invoice.ShippedDate"})
				in
				    #"Removed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

