table OrderStatus
	lineageTag: b0aa731e-1f9c-4244-a2b1-fc4aa991ed12

	column StatusID
		dataType: string
		lineageTag: fcc6288a-1e75-4c3a-b452-1ae5d973d4a3
		summarizeBy: none
		sourceColumn: StatusID

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: 9ea84cab-e99c-44c6-b914-bab20e421f42
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 925cedea-1933-4bf7-84d7-5e25c2023321
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition OrderStatus = m
		mode: import
		queryGroup: Silver
		source =
				let
				    Source = CSVs,
				    Data = Source{[#"Folder Path"=DataFolder,Name="OrdersStatus.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Data,[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","Cancell","Cancelled",Replacer.ReplaceText,{"Description"}),
				    #"Sorted Rows" = Table.Sort(#"Replaced Value",{{"StatusID", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

