table Product
	lineageTag: bcb26b49-5c38-4c86-8b1c-bb32d712b3b6

	column Product_Key
		dataType: int64
		formatString: 0
		lineageTag: d39a9f6f-2a64-458d-bd9c-3fa823d19fc1
		summarizeBy: count
		sourceColumn: Product_Key

		annotation SummarizationSetBy = Automatic

	column Supplier_Key
		dataType: int64
		formatString: 0
		lineageTag: 945ad3e7-b21c-48fc-b047-204a528ad7a0
		summarizeBy: count
		sourceColumn: Supplier_Key

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: b69d5150-1cb6-4ed1-bd20-a327b3fb697b
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Quantity Per Unit'
		dataType: string
		lineageTag: dfd9bd88-a8f5-47d8-8e8e-af5577b97c02
		summarizeBy: none
		sourceColumn: Quantity Per Unit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 372efa06-64f6-4de2-8f2e-7bec947d721e
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Units In Stock'
		dataType: int64
		formatString: 0
		lineageTag: 637af2b4-cc73-4fe6-aff2-4472c706fc25
		summarizeBy: sum
		sourceColumn: Units In Stock

		annotation SummarizationSetBy = Automatic

	column 'Units On Order'
		dataType: int64
		formatString: 0
		lineageTag: 9eb406ab-ed6d-4982-a9a3-6aea15ae8b2e
		summarizeBy: sum
		sourceColumn: Units On Order

		annotation SummarizationSetBy = Automatic

	column Discontinued
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f6974a37-8df4-4d1b-85e2-08cbf5bc8079
		summarizeBy: none
		sourceColumn: Discontinued

		annotation SummarizationSetBy = Automatic

	column 'Category Name'
		dataType: string
		lineageTag: 73d57798-3c6c-4f92-9d78-005c52f5761a
		summarizeBy: none
		sourceColumn: Category Name

		annotation SummarizationSetBy = Automatic

	column 'Category Description'
		dataType: string
		lineageTag: cd343874-2a29-4de8-b0a3-fc75ec19f759
		summarizeBy: none
		sourceColumn: Category Description

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Product,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ProductID", "Product_Key"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"CategoryID"}, stg_Category, {"CategoryKey"}, "stg_Category", JoinKind.LeftOuter),
				    #"Expanded stg_Category" = Table.ExpandTableColumn(#"Merged Queries", "stg_Category", {"CategoryName", "Description"}, {"CategoryName", "Description"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded stg_Category",{{"CategoryName", "Category Name"}, {"Description", "Category Description"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"CategoryID"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"SupplierID", "Supplier_Key"}, {"ProductName", "Product Name"}, {"QuantityPerUnit", "Quantity Per Unit"}, {"UnitPrice", "Unit Price"}, {"UnitsInStock", "Units In Stock"}, {"UnitsOnOrder", "Units On Order"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

