table Product
	lineageTag: bcb26b49-5c38-4c86-8b1c-bb32d712b3b6

	measure 'Returned Tooltip Title' = ```
			
			    "Top Five Returned Products (by $) in " & SELECTEDVALUE('Product'[Product Category], "")
			```
		isHidden
		lineageTag: af85929d-5426-488a-b80e-a74e3c5ef472

		changedProperty = IsHidden

	column Product_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d39a9f6f-2a64-458d-bd9c-3fa823d19fc1
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: b69d5150-1cb6-4ed1-bd20-a327b3fb697b
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Quantity Per Unit'
		dataType: string
		displayFolder: Unit Info
		lineageTag: dfd9bd88-a8f5-47d8-8e8e-af5577b97c02
		summarizeBy: none
		sourceColumn: Quantity Per Unit

		annotation SummarizationSetBy = Automatic

	column 'Current Unit Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unit Info
		lineageTag: 372efa06-64f6-4de2-8f2e-7bec947d721e
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Units In Stock'
		dataType: int64
		formatString: 0
		displayFolder: Unit Info
		lineageTag: 637af2b4-cc73-4fe6-aff2-4472c706fc25
		summarizeBy: sum
		sourceColumn: Units In Stock

		annotation SummarizationSetBy = User

	column 'Units On Order'
		dataType: int64
		formatString: 0
		displayFolder: Unit Info
		lineageTag: 9eb406ab-ed6d-4982-a9a3-6aea15ae8b2e
		summarizeBy: sum
		sourceColumn: Units On Order

		annotation SummarizationSetBy = User

	column 'Product Category'
		dataType: string
		lineageTag: 73d57798-3c6c-4f92-9d78-005c52f5761a
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Category Description'
		dataType: string
		lineageTag: cd343874-2a29-4de8-b0a3-fc75ec19f759
		summarizeBy: none
		sourceColumn: Product Category Description

		annotation SummarizationSetBy = Automatic

	column 'Supplier Address'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: b4820110-bf04-448b-8675-a168babceb64
		dataCategory: Address
		summarizeBy: none
		sourceColumn: Supplier Address

		annotation SummarizationSetBy = Automatic

	column 'Supplier City'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: d6586e0c-9cba-4ec7-9d2b-61d8da045a82
		dataCategory: City
		summarizeBy: none
		sourceColumn: Supplier City

		annotation SummarizationSetBy = Automatic

	column 'Supplier Company Name'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: 862a0e3a-5851-4a59-b944-b8f7f9018995
		summarizeBy: none
		sourceColumn: Supplier Company Name

		annotation SummarizationSetBy = Automatic

	column 'Supplier Contact Title'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: aa200dbd-59c4-4565-bac0-fa731c1528e4
		summarizeBy: none
		sourceColumn: Supplier Contact Title

		annotation SummarizationSetBy = Automatic

	column 'Supplier Contact Name'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: 30412a6d-1556-42b5-81ac-0188a9cdb026
		summarizeBy: none
		sourceColumn: Supplier Contact Name

		annotation SummarizationSetBy = Automatic

	column 'Supplier Country'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: fcd3f154-7e25-4290-9805-79bd2746951d
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Supplier Country

		annotation SummarizationSetBy = Automatic

	column 'Supplier Fax'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: f2668efe-fe27-445f-821f-e2d2dba397f7
		summarizeBy: none
		sourceColumn: Supplier Fax

		annotation SummarizationSetBy = Automatic

	column 'Supplier Phone'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: bc573bd6-0b4b-48f3-81fd-9459b5e7207b
		summarizeBy: none
		sourceColumn: Supplier Phone

		annotation SummarizationSetBy = Automatic

	column 'Supplier Postal Code'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: dccd965e-34b8-49e8-8c58-e10cc178cf81
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Supplier Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Supplier Region'
		dataType: string
		displayFolder: Supplier Info
		lineageTag: 63d6a038-ec95-4d8d-8ab5-9051a4867877
		summarizeBy: none
		sourceColumn: Supplier Region

		annotation SummarizationSetBy = Automatic

	column 'Product Status'
		dataType: string
		lineageTag: ba178392-66aa-41b1-b600-31a1d14c1da3
		summarizeBy: none
		sourceColumn: Product Status

		annotation SummarizationSetBy = Automatic

	hierarchy 'Supplier Geography'
		displayFolder: Supplier Info
		lineageTag: 3f011dd1-b8e9-45f4-8708-eb6b5a19882a

		level 'Supplier Country'
			lineageTag: 816a732c-2090-41cd-afad-df901d0d05a2
			column: 'Supplier Country'

		level 'Supplier Region'
			lineageTag: 704b2473-8a92-4250-a7c8-a34f54424fa0
			column: 'Supplier Region'

		level 'Supplier City'
			lineageTag: 2a443bca-3c8e-47af-bead-9ba667f38e1c
			column: 'Supplier City'

		level 'Supplier Company Name'
			lineageTag: eb6129c6-20ed-4cab-bcb5-d8fd65075667
			column: 'Supplier Company Name'

	partition Product = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Product,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ProductID", "Product_Key"}}),
				    #"Merged stg_Category" = Table.NestedJoin(#"Renamed Columns", {"CategoryID"}, stg_Category, {"CategoryKey"}, "stg_Category", JoinKind.LeftOuter),
				    #"Expanded stg_Category" = Table.ExpandTableColumn(#"Merged stg_Category", "stg_Category", {"CategoryName", "Description"}, {"CategoryName", "Description"}),
				    #"Renamed Category Columns" = Table.RenameColumns(#"Expanded stg_Category",{{"CategoryName", "Category Name"}, {"Description", "Category Description"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Category Columns",{"CategoryID"}),
				    #"Renamed More Columns" = Table.RenameColumns(#"Removed Columns",{{"SupplierID", "Supplier_Key"}, {"ProductName", "Product Name"}, {"QuantityPerUnit", "Quantity Per Unit"}, {"UnitPrice", "Unit Price"}, {"UnitsInStock", "Units In Stock"}, {"UnitsOnOrder", "Units On Order"}, {"Category Name", "Product Category"}, {"Category Description", "Product Category Description"}}),
				    #"Merged stg_Supplier" = Table.NestedJoin(#"Renamed More Columns", {"Supplier_Key"}, stg_Supplier, {"SupplierID"}, "stg_Supplier", JoinKind.LeftOuter),
				    #"Renamed Supplier Columns" = Table.RenameColumns(#"Merged stg_Supplier",{{"stg_Supplier", "Supplier"}}),
				    #"Expanded stg_Supplier" = Table.ExpandTableColumn(#"Renamed Supplier Columns", "Supplier", {"Address", "City", "CompanyName", "ContactTitle", "ContactName", "Country", "Fax", "Phone", "PostalCode", "Region"}, { "Supplier Address", "Supplier City", "Supplier Company Name", "Supplier Contact Title", "Supplier Contact Name", "Supplier Country", "Supplier Fax", "Supplier Phone", "Supplier Postal Code", "Supplier Region"}),
				    #"Removed Supplier_Key" = Table.RemoveColumns(#"Expanded stg_Supplier",{"Supplier_Key"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Supplier_Key", "Product Status", each if [Discontinued] = true then "Discontinued" else "Available"),
				    #"Removed More Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Discontinued"})
				in
				    #"Removed More Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

