table Shipper
	lineageTag: 7b2b8011-43b4-4750-afd5-9a970645aa98

	column Shipper_Key
		dataType: int64
		formatString: 0
		lineageTag: 4be7527b-f397-455f-b3dd-66ae4c9381e3
		summarizeBy: count
		sourceColumn: Shipper_Key

		annotation SummarizationSetBy = Automatic

	column 'Shipper Name'
		dataType: string
		lineageTag: 53172c0f-8f8b-416e-a1e1-9a826d4a6419
		summarizeBy: none
		sourceColumn: Shipper Name

		annotation SummarizationSetBy = Automatic

	column 'Shipper Phone'
		dataType: string
		lineageTag: d25bcc82-c164-4589-a302-75c0803619a5
		summarizeBy: none
		sourceColumn: Shipper Phone

		annotation SummarizationSetBy = Automatic

	partition Shipper = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Shipper,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ShipperID", "Shipper_Key"}, {"CompanyName", "Shipper Name"}, {"Phone", "Shipper Phone"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

