table Shipper
	lineageTag: 1f50d0b1-63bc-473b-83a0-b50a959f5189

	column ShipperID
		dataType: int64
		formatString: 0
		lineageTag: 272f0235-b9aa-43d3-a706-f90443ce9e36
		summarizeBy: count
		sourceColumn: ShipperID

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: b29b9d76-4c0b-4e8b-a144-d7063ead899f
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 474c9d55-2912-4fa5-ad43-09410336a751
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	partition Shipper = m
		mode: import
		queryGroup: Silver
		source =
				let
				    Source = CSVs,
				    Data = Source{[#"Folder Path"=DataFolder,Name="Shippers.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Data,[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ShipperID", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"ShipperID", "CompanyName", "Phone"}),
				    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"ShipperID", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

