table Shipment
	lineageTag: 485d58a9-1fd0-4d60-92ea-b5da23dc9d2a

	column Shipment_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b53dfcbe-ce75-4040-8868-6133d02a67e9
		summarizeBy: none
		sourceColumn: Shipment_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ship To'
		dataType: string
		lineageTag: e7eede35-d3db-45ad-bc98-2699ae0a98ff
		summarizeBy: none
		sourceColumn: Ship To

		annotation SummarizationSetBy = Automatic

	column 'Ship PostalCode'
		dataType: string
		lineageTag: 8525bf1e-381a-4d2a-ab59-1fc5c1c34716
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Ship PostalCode

		annotation SummarizationSetBy = Automatic

	column 'Ship Region'
		dataType: string
		lineageTag: d0eafbf5-0670-4b14-ae77-dd801c7a0a00
		summarizeBy: none
		sourceColumn: Ship Region

		annotation SummarizationSetBy = Automatic

	column 'Ship Country'
		dataType: string
		lineageTag: b1cd4a6d-04e9-4353-af0a-40ef3ae8a372
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Ship Country

		annotation SummarizationSetBy = Automatic

	column 'Ship City'
		dataType: string
		lineageTag: 49b975b1-28e0-44cb-b44b-3d8c70cf5f31
		dataCategory: City
		summarizeBy: none
		sourceColumn: Ship City

		annotation SummarizationSetBy = Automatic

	column 'Ship Address'
		dataType: string
		lineageTag: 4017e8e6-4e32-412f-b05e-f2a782bb55c6
		dataCategory: Address
		summarizeBy: none
		sourceColumn: Ship Address

		annotation SummarizationSetBy = Automatic

	hierarchy 'Ship To Location'
		lineageTag: ef630e5c-28a6-4aec-8789-b5eb98c8f31a

		level 'Ship Country'
			lineageTag: 9f760b22-efaa-4eca-9655-ddd5680b068c
			column: 'Ship Country'

		level 'Ship Region'
			lineageTag: e4e37c4e-6c7e-465d-88b4-c1f9bf67f53f
			column: 'Ship Region'

		level 'Ship City'
			lineageTag: a29e3692-81cb-458c-b9f2-727b62b93c49
			column: 'Ship City'

		level 'Ship To'
			lineageTag: d3629c32-b0c4-4e47-a67d-781d1b3ce2d9
			column: 'Ship To'

	partition Shipment = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Invoice,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"RequiredDate", "ShipName", "OrderID", "ShipPostalCode", "ShipRegion", "ShipCountry", "ShipCity", "ShipAddress"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Other Columns",{{"RequiredDate", Order.Ascending}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows",{"RequiredDate"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"ShipName", "Ship To"}, {"ShipPostalCode", "Ship PostalCode"}, {"ShipRegion", "Ship Region"}, {"ShipCountry", "Ship Country"}, {"ShipCity", "Ship City"}, {"ShipAddress", "Ship Address"}}),
				    #"Grouped Rows" = Table.Group(#"Renamed Columns", {"Ship To", "Ship PostalCode", "Ship Region", "Ship Country", "Ship City", "Ship Address"}, {{"Orders", each _, type table [OrderID=nullable text]}}),
				    #"Added Index" = Table.AddIndexColumn(#"Grouped Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Index" = Table.RenameColumns(#"Added Index",{{"Index", "Shipment_Key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Index",{"Shipment_Key", "Ship To", "Ship PostalCode", "Ship Region", "Ship Country", "Ship City", "Ship Address", "Orders"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

