table Supplier
	lineageTag: 3723e5ba-e229-4270-9529-7d158b6806d9

	column Supplier_Key
		dataType: int64
		formatString: 0
		lineageTag: a7b1de27-430f-4105-ab7d-a4687edda2bb
		summarizeBy: count
		sourceColumn: Supplier_Key

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: ec972962-8f8f-4c71-acfc-83376d99ce4c
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 263e2d52-cb1b-4bb2-b308-b50c56d392c7
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: c2e3a61d-63ad-4bf1-8c4f-d2dc2bc196b3
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column ContactTitle
		dataType: string
		lineageTag: e051669a-69e2-4020-94f2-9135323da000
		summarizeBy: none
		sourceColumn: ContactTitle

		annotation SummarizationSetBy = Automatic

	column ContactName
		dataType: string
		lineageTag: 575b62ac-8a15-46ae-8b60-5cf6826def7e
		summarizeBy: none
		sourceColumn: ContactName

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 04741eec-3c49-482e-87b6-4b8f4fbbc40a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: bc52669e-aff6-42f1-a5e3-5e2a80f6d01d
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 701bd8bb-da74-4473-b9c8-88d8c2404477
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: f273c0bb-afb9-4329-8713-2e7d2cce805f
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 85f22811-2f4d-4944-9409-de3420667988
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Supplier = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = stg_Supplier,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"SupplierID", "Supplier_Key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

